"""removed counter models and chnaged column names

Revision ID: 0a2f776eebbc
Revises: 376a90eb8e7c
Create Date: 2024-08-25 12:41:41.416189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2f776eebbc'
down_revision: Union[str, None] = '376a90eb8e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('five_generator_counter')
    op.drop_table('six_generator_counter')
    op.add_column('five_generator', sa.Column('short_key', sa.String(), nullable=True))
    op.drop_column('five_generator', 'short_url')
    op.add_column('six_generator', sa.Column('short_key', sa.String(), nullable=True))
    op.drop_column('six_generator', 'hits')
    op.drop_column('six_generator', 'short_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('six_generator', sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('six_generator', sa.Column('hits', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('six_generator', 'short_key')
    op.add_column('five_generator', sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('five_generator', 'short_key')
    op.create_table('six_generator_counter',
    sa.Column('count', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('count', name='six_generator_counter_pkey')
    )
    op.create_table('five_generator_counter',
    sa.Column('count', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('count', name='five_generator_counter_pkey')
    )
    # ### end Alembic commands ###
