"""created table for storing generated short urls and counter table for length 5 and 6

Revision ID: 2b336e01c521
Revises: 1d0e7cec2f64
Create Date: 2024-08-05 23:02:20.559393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b336e01c521'
down_revision: Union[str, None] = '1d0e7cec2f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('five_generator_counter',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('count')
    )
    op.create_table('six_generator_counter',
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('count')
    )
    op.create_table('five_generator',
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('short_url')
    )
    op.create_table('six_generator',
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('six_generator')
    op.drop_table('five_generator')
    op.drop_table('six_generator_counter')
    op.drop_table('five_generator_counter')
    # ### end Alembic commands ###
